name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up jdk 23
        uses: actions/setup-java@v3
        with:
          java-version: 23
          distribution: 'temurin'

      - name: starting postgresql server
        run: sudo systemctl start postgresql.service
#
#      - name: set up postgres user and create database
#        run: |


      - name: gradle wrapper build
        run: gradle wrapper --gradle-version 8.10

      - name: cache gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: run checkstyle
        run: | 
          chmod +x ./gradlew
          ./gradlew checkstyleMain checkstyleTest

      - name: run tests
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: build project
        run: |
          chmod +x ./gradlew
          ./gradlew build