name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mira
          POSTGRES_DB: oms_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up jdk 23
        uses: actions/setup-java@v3
        with:
          java-version: 23
          distribution: 'temurin'

      - name: gradle wrapper build
        run: gradle wrapper --gradle-version 8.10

      - name: cache gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: set ./gradlew executable
        run: chmod +x ./gradlew

      - name: run checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: run tests
        run: ./gradlew test

      - name: build project
        run: ./gradlew build